// All visible website copy. Strings may contain trusted inline HTML such as <em>.

export const siteUrl = 'https://imagezoom.zshnb.com'
export const updated = '2026-09-30'
export const contactEmail = 'a857681664@gmail.com'
export const storeUrl = 'https://chromewebstore.google.com/detail/ai-image-upscaler-zoom-%E2%80%93/lmlmlkdfgcbickfngnhnmfajmenoeoll'

export const routes = { en: '/', zh: '/zh-cn/' }
export const nativeRoutes = { en: '/local-ai-image-upscaler/', zh: '/zh-cn/local-ai-image-upscaler/' }

// Replace these files in public/media/ with real product material before publishing.
// Set recording to { src, poster, duration, uploadDate } once a real MP4 exists.
export const media = {
  before: { src: '/media/ai-before.webp', width: 540, height: 420 },
  after: { src: '/media/ai-after.webp', width: 540, height: 420 },
  street: { src: '/media/demo-street.webp', width: 760, height: 420 },
  recording: null,
}

export const ui = {
  en: {
    htmlLang: 'en',
    ogLocale: 'en_US',
    storeLang: 'en',
    skip: 'Skip to content',
    nav: [['#how-it-works', 'How it works'], ['#features', 'Features'], ['#ai-upscaler', 'AI upscaler'], ['#privacy', 'Privacy'], ['#faq', 'FAQ']],
    navLabel: 'Main',
    langSwitch: '中文',
    langSwitchLabel: 'Switch to Chinese',
    install: 'Add to Chrome',
    installFree: 'Add to Chrome, it’s free',
    footerTagline: 'The image zoom extension for Chrome, with optional local AI enhancement.',
    footerProduct: 'Product',
    footerResources: 'Resources',
    nativeGuide: 'Local AI setup guide',
    footerLanguage: 'Language',
    footerLinks: { how: 'How it works', features: 'Features', ai: 'AI image upscaler', faq: 'FAQ', store: 'Chrome Web Store', privacy: 'Privacy Policy', terms: 'Terms of Service' },
    footerContact: 'Contact',
    footerLegal: 'Chrome is a trademark of Google LLC. Click Image Zoom is not affiliated with Google.',
    breadcrumbHome: 'Home',
    breadcrumbLabel: 'Breadcrumb',
    compareLabel: 'Drag to compare the original image with the AI clarity result',
    compareBefore: 'Original',
    compareAfter: 'AI clarity 4x',
    compareAltBefore: 'Original web image before AI upscaling',
    compareAltAfter: 'The same image after local 4x AI upscaling',
    demo: {
      label: 'Interactive demo of the Click Image Zoom viewer',
      address: 'garden-shop.example/oxalis',
      kicker: 'Garden · Ground cover',
      title: 'Pink wood sorrel, 12 plugs',
      price: '$24.00',
      cart: 'Add to cart',
      related: 'You may also like',
      flowerAlt: 'Pink wood sorrel flowers growing between bamboo stakes',
      flowerOpen: 'Open the flower photo in the demo viewer',
      streetAlt: 'Rainy city street at dusk with neon shop signs',
      streetOpen: 'Open the street photo in the demo viewer',
      key: 'Shift',
      hint: 'Live demo: hold <kbd>Shift</kbd> and click a photo, scroll to zoom, drag to pan.',
      hintToast: 'Hold Shift while you click',
      pause: 'Pause',
      play: 'Play',
      busy: 'Creating a clearer image',
      ready: 'AI clarity ready',
      copied: 'Copied link',
      copyFailed: 'Copy failed',
      tools: [['open', 'Open'], ['copy', 'Copy'], ['save', 'Save'], ['close', 'Close']],
    },
  },
  zh: {
    htmlLang: 'zh-CN',
    ogLocale: 'zh_CN',
    storeLang: 'zh-CN',
    skip: '跳到正文',
    nav: [['#how-it-works', '使用方法'], ['#features', '功能'], ['#ai-upscaler', 'AI 高清放大'], ['#privacy', '隐私'], ['#faq', '常见问题']],
    navLabel: '主导航',
    langSwitch: 'English',
    langSwitchLabel: '切换到英文',
    install: '添加到 Chrome',
    installFree: '免费添加到 Chrome',
    footerTagline: '适用于 Chrome 的网页图片放大插件，可选本地 AI 高清增强。',
    footerProduct: '产品',
    footerResources: '资源',
    nativeGuide: '本地 AI 安装指南',
    footerLanguage: '语言',
    footerLinks: { how: '使用方法', features: '功能', ai: 'AI 图片高清放大', faq: '常见问题', store: 'Chrome 应用商店', privacy: '隐私政策（英文）', terms: '服务条款（英文）' },
    footerContact: '联系',
    footerLegal: 'Chrome 是 Google LLC 的商标。Click Image Zoom 与 Google 无关联。',
    breadcrumbHome: '首页',
    breadcrumbLabel: '当前位置',
    compareLabel: '拖动对比原图与 AI 清晰增强结果',
    compareBefore: '原图',
    compareAfter: 'AI 清晰 4 倍',
    compareAltBefore: 'AI 高清放大前的网页原图',
    compareAltAfter: '经过本地 4 倍 AI 高清放大后的同一张图片',
    demo: {
      label: 'Click Image Zoom 查看器交互演示',
      address: 'garden-shop.example/oxalis',
      kicker: '园艺 · 地被植物',
      title: '粉花酢浆草，12 株',
      price: '¥168',
      cart: '加入购物车',
      related: '猜你喜欢',
      flowerAlt: '竹竿之间盛开的粉色酢浆草',
      flowerOpen: '在演示查看器中打开花卉图片',
      streetAlt: '傍晚下雨的城市街道和霓虹招牌',
      streetOpen: '在演示查看器中打开街景图片',
      key: 'Shift',
      hint: '在线演示：按住 <kbd>Shift</kbd> 点击图片，滚轮放大，拖动查看。',
      hintToast: '请按住 Shift 再点击',
      pause: '暂停',
      play: '播放',
      busy: '正在生成更清晰的图片',
      ready: 'AI 清晰已就绪',
      copied: '已复制链接',
      copyFailed: '复制失败',
      tools: [['open', '打开'], ['copy', '复制'], ['save', '保存'], ['close', '关闭']],
    },
  },
}

export const home = {
  en: {
    title: 'Image Zoom Extension for Chrome | Click Image Zoom',
    description: 'Free image zoom extension for Chrome. Click web images to zoom up to 10x and pan. Optional local AI image upscaler with a separately installed Real-ESRGAN helper.',
    hero: {
      badge: 'Free Chrome extension · No account · Runs locally',
      h1: 'The <em>image zoom</em> extension for Chrome',
      lead: 'Hold a key. Click an image. Zoom up to 10x, explore every detail, and optionally enhance small pictures with local AI.',
      secondary: 'See how it works',
    },
    strip: {
      label: 'Made for the images you inspect every day',
      items: [['bag', 'Product photos'], ['search', 'Image search'], ['monitor', 'Screenshots'], ['chart', 'Charts & diagrams']],
    },
    pillars: {
      h2: 'One shortcut to <em>open, zoom, and enhance</em> any web image',
      cards: [
        { visual: 'keys', title: 'Shortcut-click viewer', text: 'Hold your key and click. The image opens in a clean viewer on top of the page, and nothing pops up when your pointer just passes over a picture.' },
        { visual: 'zoom', title: '10x zoom and drag to pan', text: 'Scroll to zoom up to 10x, then drag to check every corner. Close the viewer and you are exactly where you left off.' },
        { visual: 'ai', title: 'Optional local 4x AI', text: 'AI tries a separately installed Real-ESRGAN helper first, then browser AI. Image processing stays on your device.', link: 'Set up local AI' },
      ],
    },
    statement: {
      quote: 'Hover previews pop up whenever your mouse moves. Click Image Zoom waits until you ask: <em>hold a key, click, and look closer.</em>',
      by: 'The idea behind Click Image Zoom',
      facts: [['10x', 'maximum zoom'], ['4x', 'local AI upscale'], ['8', 'trigger keys'], ['$0', 'no account needed']],
    },
    steps: {
      eyebrow: 'How it works',
      h2: 'From thumbnail to detail <em>in four steps</em>',
      label: 'Steps for zooming a web image',
      items: [
        { title: 'Hold & click', text: 'Pick Shift, Alt, Ctrl, or Command, left or right, in the popup. Hold it and click any image to open the viewer on the same page.' },
        { title: 'Zoom', text: 'Scroll the mouse wheel to zoom smoothly up to 10x. The viewer tries the sharpest image source the page provides.' },
        { title: 'Pan', text: 'Click and drag to move around the enlarged image. Press Esc or Close to return to the page.' },
        { title: 'Enhance', text: 'Choose AI clarity in the popup and trigger it on first zoom or viewer open. An installed local helper is tried first, with browser AI as a fallback.' },
      ],
      popup: { heading: 'Click Image Zoom', key: 'Activation key', keyValue: 'Left Shift', quality: 'Enlarged image quality', qualityValue: 'AI clarity (Recommended)', site: 'Current site', siteValue: 'Enabled on this site' },
      zoomLabel: 'Mouse wheel',
      panLabel: 'Drag to pan',
    },
    features: {
      eyebrow: 'Features',
      h2: 'A focused image viewer <em>with the controls you actually use</em>',
      items: [
        ['layers', 'Sharpest available source', 'Reads srcset, picture sources, and lazy-load attributes to show a higher-resolution image when the page offers one.'],
        ['external', 'Open, copy, save', 'Open the original image, copy its link, or save it straight from the viewer toolbar.'],
        ['keyboard', '8 trigger keys', 'Left or right Shift, Alt, Ctrl, or Command. Pick the one that does not clash with your sites.'],
        ['toggle', 'Per-site switch', 'Turn Click Image Zoom off for a site from the popup, and back on at any time.'],
        ['refresh', 'Dynamic pages', 'Works with infinite scroll, lazy-loaded galleries, and images inside buttons.'],
        ['gauge', 'Faster or Better quality', 'Choose a model in the popup. AI uses the separately installed local helper first, then browser AI if needed.'],
        ['maximize', 'AI size limit', 'Cap the largest image sent to local AI, from about 800 × 600 up to 3000 × 2000.'],
        ['shield', 'Viewer stays usable', 'If native AI fails, browser AI is tried next. If both fail, Lanczos sharpening takes over.'],
      ],
    },
    recording: {
      eyebrow: 'Real recording',
      h2: 'Watch it work on <em>a real webpage</em>',
      text: 'An unedited screen recording in Chrome: shortcut click, wheel zoom, drag to pan, and local AI clarity.',
      name: 'Click Image Zoom in Chrome: shortcut click, 10x zoom, and local AI clarity',
      placeholder: 'Screen recording placeholder. Replace with the real MP4 before publishing.',
    },
    ai: {
      eyebrow: 'Optional local AI image upscaler',
      h2: 'Real-ESRGAN clarity, on your own device',
      text: 'Create a 4x version of small images with a separately installed Real-ESRGAN helper. AI tries that helper first, with browser AI as a fallback. Images are fetched from their source website; enhancement does not upload pixels to a cloud AI service.',
      bullets: ['4x Real-ESRGAN upscaling', 'Native helper setup on macOS or Linux', 'Faster or Better quality models', 'Trigger on first zoom or viewer open'],
      setup: 'Install the local AI helper',
      limit: 'AI makes existing detail easier to see. It cannot recover text or facts that were never in the original image.',
    },
    privacy: {
      eyebrow: 'Privacy',
      h2: 'Private <em>by design</em>',
      text: 'Your images, settings, and browsing stay yours.',
      items: [
        ['cpu', 'Local processing', 'The optional native helper and browser AI fallback both process images on your device, without a cloud AI upload.'],
        ['user', 'No account', 'No sign-up, login, or subscription for the viewer or the local AI.'],
        ['eyeOff', 'No tracking', 'No analytics, advertising trackers, or remote crash reporting in the extension.'],
        ['lock', 'Minimal permissions', 'Storage, downloads, and optional native messaging, plus site access to read the image you click.'],
        ['toggle', 'Settings stay local', 'Your trigger key, AI preferences, and disabled sites live in Chrome local storage.'],
        ['shield', 'Safe image requests', 'Private network addresses are blocked, redirects are not followed, and non-image responses are rejected.'],
      ],
      link: 'Read the privacy policy',
    },
    uses: {
      eyebrow: 'Use cases',
      h2: 'Built for the way <em>you browse</em>',
      label: 'Use cases',
      items: [
        { tab: 'Online shopping', title: 'Check product photos before you buy', text: 'Zoom into fabric, stitching, labels, and small print on product images without opening every listing in a new tab.', bullets: ['Inspect textures at up to 10x', 'Read tiny size charts and labels', 'Compare details across listings'], image: 'before' },
        { tab: 'Image search', title: 'Look closer at search results in place', text: 'Open image-search thumbnails in the viewer, check them at a larger size, then keep scrolling from the same spot.', bullets: ['No new tab for every result', 'Uses a higher-resolution source when available', 'Copy the image link in one click'], image: 'street' },
        { tab: 'Charts & screenshots', title: 'Read the small text in charts and screenshots', text: 'Zoom into axis labels, dashboards, UI screenshots, and diagrams in articles and docs. Use AI clarity when a screenshot is soft.', bullets: ['Drag across wide diagrams', 'AI clarity for soft screenshots', 'Verify numbers against the source'], image: 'after' },
        { tab: 'Social & news', title: 'Open feed photos without losing your place', text: 'See article photos and social thumbnails at a larger size, then close the viewer and keep reading.', bullets: ['Works on infinite-scroll feeds', 'Opens only when you ask', 'Turn it off per site'], image: 'street' },
      ],
    },
    faq: {
      h2: 'Frequently asked <em>questions</em>',
      items: [
        ['What is Click Image Zoom?', 'Click Image Zoom is a free image zoom extension for Chrome. Hold a key and click an image to open an in-page viewer, zoom up to 10x, and drag to pan. Optional AI tries a separately installed local Real-ESRGAN helper first, then browser AI.'],
        ['How do I zoom an image in Chrome with it?', 'Install the extension from the Chrome Web Store and pick a trigger key in the popup (Left Shift by default). Hold that key and click any image, scroll to zoom, drag to pan, and press Esc or Close to return to the page.'],
        ['Is Click Image Zoom free?', 'Yes. The viewer and the local AI enhancement are currently free to use, with no account or subscription.'],
        ['How is it different from hover zoom extensions?', 'Hover zoom extensions show a preview whenever your pointer passes over an image. Click Image Zoom opens only when you hold your key and click, and adds 10x wheel zoom, drag to pan, and optional local AI upscaling.'],
        ['Does the AI image upscaler upload my images?', 'No. The extension may fetch the original from its source website, but enhancement stays on your device. An installed native helper processes pixels outside Chrome on the same device; browser AI is the fallback. Neither path uploads pixels to a cloud AI service.'],
        ['Do I need to install a local AI helper?', 'The image viewer works without one. To use native Real-ESRGAN, separately install the CLI, models, and Chrome Native Messaging helper on macOS or Linux. AI then tries it automatically. See the <a href="/local-ai-image-upscaler/">local AI setup guide</a>.'],
        ['Can AI recover details that are not in the original?', 'No. AI can make existing edges and textures easier to see, and it may introduce artifacts. Always check important text, prices, or numbers against the original image.'],
        ['Does it work on every website?', 'It works on most regular web pages, including dynamic and lazy-loaded ones, but some sites restrict access to their images. You can turn the extension off for any site from the popup.'],
        ['Can I turn the AI off?', 'Yes. In the popup, choose Quick sharpening or Zoom only under Enlarged image quality.'],
      ],
    },
    cta: {
      h2: 'Look closer at <em>every web image</em>',
      text: 'Install Click Image Zoom for free, hold your key, and click.',
    },
  },
  zh: {
    title: 'Chrome 图片放大插件：网页图片放大与 AI 高清 | Click Image Zoom',
    description: '免费的 Chrome 图片放大插件。按住快捷键点击网页图片，在原页面放大到 10 倍并拖动查看；可选本地 AI 图片高清放大，优先使用单独安装的 Real-ESRGAN 本地助手。',
    hero: {
      badge: '免费 Chrome 插件 · 无需账号 · 本地运行',
      h1: 'Chrome <em>图片放大</em>插件',
      lead: '按住快捷键，点击网页图片。最高放大 10 倍，拖动查看每处细节，还可选择本地 AI 让小图更清晰。',
      secondary: '了解使用方法',
    },
    strip: {
      label: '为你每天要仔细看的图片而做',
      items: [['bag', '商品图片'], ['search', '图片搜索'], ['monitor', '网页截图'], ['chart', '图表与示意图']],
    },
    pillars: {
      h2: '一个快捷键，<em>打开、放大、增强</em>网页图片',
      cards: [
        { visual: 'keys', title: '快捷键点击查看', text: '按住快捷键再点击，图片会在当前页面上方的查看器中打开。鼠标只是经过图片时，不会弹出任何东西。' },
        { visual: 'zoom', title: '10 倍放大，拖动查看', text: '滚轮最高放大 10 倍，拖动检查每个角落。关闭查看器后，页面仍停在原来的位置。' },
        { visual: 'ai', title: '可选本地 4 倍 AI', text: 'AI 优先尝试单独安装的 Real-ESRGAN 本地助手，再尝试浏览器 AI。图片处理始终留在你的设备上。', link: '设置本地 AI' },
      ],
    },
    statement: {
      quote: '悬停预览总是在鼠标移动时弹出来。Click Image Zoom 只在你需要时出现：<em>按住按键，点击，看清楚。</em>',
      by: 'Click Image Zoom 的设计理念',
      facts: [['10 倍', '最高放大'], ['4 倍', '本地 AI 增强'], ['8 个', '可选触发键'], ['免费', '无需账号']],
    },
    steps: {
      eyebrow: '使用方法',
      h2: '从缩略图到细节，<em>只需四步</em>',
      label: '放大网页图片的步骤',
      items: [
        { title: '按住并点击', text: '在插件弹窗里选择左侧或右侧的 Shift、Alt、Ctrl 或 Command，按住它点击任意图片，查看器会在当前页面打开。' },
        { title: '滚轮放大', text: '滚动鼠标滚轮，平滑放大到 10 倍。查看器会优先尝试网页提供的更高清图片来源。' },
        { title: '拖动查看', text: '按住鼠标拖动，查看放大后图片的各个部分。按 Esc 或点击关闭即可回到页面。' },
        { title: 'AI 增强', text: '在弹窗选择 AI 清晰，设为首次放大或打开图片时触发。优先尝试已安装的本地助手，失败后再尝试浏览器 AI。' },
      ],
      popup: { heading: 'Click Image Zoom', key: '触发按键', keyValue: '左 Shift', quality: '放大图片画质', qualityValue: 'AI 清晰（推荐）', site: '当前网站', siteValue: '已在此网站启用' },
      zoomLabel: '鼠标滚轮',
      panLabel: '拖动查看',
    },
    features: {
      eyebrow: '功能',
      h2: '专注的图片查看器，<em>只保留真正常用的操作</em>',
      items: [
        ['layers', '优先高清来源', '读取 srcset、picture 和懒加载属性，网页提供更高清图片时优先显示。'],
        ['external', '打开、复制、保存', '在查看器工具栏直接打开原图、复制图片链接或保存图片。'],
        ['keyboard', '8 个触发键', '左侧或右侧的 Shift、Alt、Ctrl、Command，选一个不和网站快捷键冲突的。'],
        ['toggle', '按网站开关', '在插件弹窗中为某个网站关闭 Click Image Zoom，随时可以重新开启。'],
        ['refresh', '支持动态网页', '适用于无限滚动、懒加载图库和按钮内的图片。'],
        ['gauge', '速度或画质优先', '在弹窗选择模型。AI 优先使用单独安装的本地助手，必要时回退到浏览器 AI。'],
        ['maximize', 'AI 尺寸上限', '限制送入本地 AI 的最大图片尺寸，从约 800 × 600 到 3000 × 2000。'],
        ['shield', '查看器照常可用', '本地助手失败后尝试浏览器 AI；两者都不可用时改用 Lanczos 快速清晰。'],
      ],
    },
    recording: {
      eyebrow: '真实录屏',
      h2: '看看它在<em>真实网页</em>上的效果',
      text: '在 Chrome 中未经剪辑的真实录屏：快捷键点击、滚轮放大、拖动查看和本地 AI 清晰。',
      name: 'Click Image Zoom 在 Chrome 中的使用：快捷键点击、10 倍放大和本地 AI 清晰',
      placeholder: '录屏占位。发布前请替换为真实 MP4。',
    },
    ai: {
      eyebrow: '可选本地 AI 图片高清放大',
      h2: 'Real-ESRGAN 高清增强，留在你的设备上',
      text: '单独安装 Real-ESRGAN 本地助手，为小图生成 4 倍版本。AI 优先尝试本地助手，失败后回退到浏览器 AI。原图会从来源网站获取，增强过程不会把像素上传到云端 AI 服务。',
      bullets: ['Real-ESRGAN 4 倍放大', '本地助手支持 macOS 或 Linux 安装', '速度优先或画质优先模型', '首次放大或打开图片时触发'],
      setup: '安装本地 AI 助手',
      limit: 'AI 能让已有细节更容易看清，但无法恢复原图中本来不存在的文字或信息。',
    },
    privacy: {
      eyebrow: '隐私',
      h2: '<em>从设计上</em>保护隐私',
      text: '你的图片、设置和浏览记录都只属于你。',
      items: [
        ['cpu', '本地处理', '可选本地助手与浏览器 AI 后备都在你的设备上处理图片，不上传到云端 AI 服务。'],
        ['user', '无需账号', '查看器和本地 AI 都不需要注册、登录或订阅。'],
        ['eyeOff', '不做追踪', '插件中没有统计分析、广告追踪或远程崩溃上报。'],
        ['lock', '最少权限', '仅使用存储、下载和可选的本地消息通信权限，以及读取你点击图片所需的网站访问权限。'],
        ['toggle', '设置保存在本地', '触发键、AI 偏好和已禁用的网站都保存在 Chrome 本地存储中。'],
        ['shield', '安全的图片请求', '拦截私有网络地址，不跟随重定向，拒绝非图片响应。'],
      ],
      link: '阅读隐私政策（英文）',
    },
    uses: {
      eyebrow: '使用场景',
      h2: '贴合<em>你的浏览习惯</em>',
      label: '使用场景',
      items: [
        { tab: '网上购物', title: '下单前看清商品图', text: '放大查看面料、走线、标签和小字，不用把每个商品都在新标签页打开。', bullets: ['最高 10 倍查看材质', '看清小号尺码表和标签', '在不同商品之间对比细节'], image: 'before' },
        { tab: '图片搜索', title: '在搜索结果页直接看大图', text: '在查看器中打开图片搜索的缩略图，看大图后接着从原位置往下浏览。', bullets: ['不用为每个结果开新标签页', '有更高清来源时优先使用', '一键复制图片链接'], image: 'street' },
        { tab: '图表与截图', title: '看清图表和截图里的小字', text: '放大文章和文档中的坐标轴标签、仪表盘、界面截图和示意图。截图发糊时可以用 AI 清晰。', bullets: ['拖动查看很宽的示意图', '模糊截图可用 AI 清晰', '重要数字请以原图为准'], image: 'after' },
        { tab: '社交与新闻', title: '打开信息流图片，不丢失浏览位置', text: '放大查看文章配图和社交媒体缩略图，关闭查看器后继续阅读。', bullets: ['支持无限滚动的信息流', '只在你需要时打开', '可以按网站关闭'], image: 'street' },
      ],
    },
    faq: {
      h2: '常见<em>问题</em>',
      items: [
        ['Click Image Zoom 是什么？', 'Click Image Zoom 是免费的 Chrome 图片放大插件。按住快捷键点击图片，在原页面查看器里放大到 10 倍、拖动查看。可选 AI 优先尝试单独安装的 Real-ESRGAN 本地助手，再尝试浏览器 AI。'],
        ['怎么用它在 Chrome 里放大图片？', '从 Chrome 应用商店安装插件，在弹窗中选择触发键（默认左 Shift）。按住这个键点击任意图片，滚轮放大，拖动查看，按 Esc 或点击关闭即可回到页面。'],
        ['Click Image Zoom 免费吗？', '免费。查看器和本地 AI 增强目前都可以免费使用，无需账号或订阅。'],
        ['它和悬停放大插件有什么不同？', '悬停放大插件会在鼠标经过图片时自动弹出预览。Click Image Zoom 只有在你按住按键并点击时才打开，并提供 10 倍滚轮放大、拖动查看和可选的本地 AI 高清放大。'],
        ['AI 图片高清放大会上传我的图片吗？', '不会。插件可能从来源网站获取原图；增强始终留在设备上。已安装的本地助手会在 Chrome 之外处理像素，浏览器 AI 则作为后备，两条路径都不会上传像素到云端 AI 服务。'],
        ['需要安装本地 AI 助手吗？', '普通图片查看器不需要。使用原生 Real-ESRGAN 时，需在 macOS 或 Linux 单独安装 CLI、模型与 Chrome Native Messaging 助手，之后 AI 会自动优先尝试它。请查看<a href="/zh-cn/local-ai-image-upscaler/">本地 AI 安装指南</a>。'],
        ['AI 能恢复原图里没有的细节吗？', '不能。AI 可以让已有的边缘和纹理更容易看清，也可能产生伪影。重要的文字、价格或数字请以原图为准。'],
        ['所有网站都能用吗？', '适用于大多数普通网页，包括动态加载和懒加载的页面，但部分网站会限制图片访问。你可以在弹窗中为任意网站关闭插件。'],
        ['可以关闭 AI 吗？', '可以。在弹窗的“放大图片画质”中选择“快速清晰”或“仅缩放”。'],
      ],
    },
    cta: {
      h2: '看清<em>每一张网页图片</em>',
      text: '免费安装 Click Image Zoom，按住快捷键，点击即可。',
    },
  },
}

export const nativeSetup = {
  en: {
    title: 'Local Real-ESRGAN Image Upscaler for Chrome | Click Image Zoom',
    description: 'Set up a separate local Real-ESRGAN helper for Chrome. Upscale web images 4x on macOS or Linux, with browser AI fallback and no cloud upload of image pixels.',
    eyebrow: 'Optional local AI · Setup guide',
    h1: 'Upscale web images with local <span class="modelName">Real-ESRGAN</span>',
    lead: 'Connect Click Image Zoom to Real-ESRGAN on your device. Install the local helper once; AI then tries it automatically before browser AI.',
    setupLink: 'Set up the local helper',
    back: 'Back to the image viewer',
    flow: {
      h2: 'How the local path works',
      text: 'The extension fetches the original image from its source website. When AI clarity is triggered, Chrome sends the image to an installed local helper through Native Messaging.',
      nodes: [['Chrome extension', 'Select an image and trigger AI clarity'], ['Local helper', 'Chrome Native Messaging · Python'], ['Real-ESRGAN CLI', 'Local model inference · 4x output']],
      note: 'Native path: the result returns to the viewer. If the helper is missing or fails, the extension tries its browser AI fallback using LiteRT/WebGPU. If that also fails, it uses Lanczos sharpening. Image pixels are not uploaded to a cloud AI service.',
    },
    requirements: {
      h2: 'Before you install',
      text: 'The local helper is optional. The free image viewer, 10x zoom, and panning work without it. Native AI creates a fixed 4x result; it cannot recover facts or text absent from the original.',
      items: [
        ['Supported setup', 'Google Chrome on macOS or Linux. The project’s Native Messaging installer does not support Windows, even though the upstream CLI has a Windows release.'],
        ['Python and local files', 'The installer calls /usr/bin/python3, and the helper also needs python3 on PATH. Both must be available; only Python’s standard library is used, with no pip packages to install. Keep the CLI executable and its .param/.bin model files in permanent local locations.'],
        ['Device requirements', 'Use an upstream CLI build compatible with your operating system and GPU. Runtime, memory use, and model availability vary by device.'],
      ],
    },
    install: {
      h2: 'Install and connect in four steps',
      intro: 'Use your installed extension’s actual ID and absolute local paths.',
      steps: [
        {
          title: 'Install the extension and copy its ID',
          body: 'Add Click Image Zoom from the Chrome Web Store. Open <code>chrome://extensions</code>, turn on Developer mode, and copy the ID shown for Click Image Zoom. Use that exact ID, including for an unpacked development build.',
        },
        {
          title: 'Download the CLI and model files',
          body: 'Download the correct operating-system archive from the <a href="https://github.com/xinntao/Real-ESRGAN-ncnn-vulkan/releases" target="_blank" rel="noopener">official Real-ESRGAN-ncnn-vulkan releases</a> and extract it. The model directory must contain <code>realesrgan-x4plus.param</code> and <code>realesrgan-x4plus.bin</code>. For the Faster model, also keep the <code>realesr-general-x4v3.param</code> and <code>realesr-general-x4v3.bin</code> pair. Read the <a href="https://github.com/xinntao/Real-ESRGAN" target="_blank" rel="noopener">official Real-ESRGAN project</a> for model background.',
        },
        {
          title: 'Register the local helper with Chrome',
          body: 'Download both <a href="/downloads/native-host/install.sh" download="install.sh">install.sh</a> and <a href="/downloads/native-host/host.py" download="host.py">host.py</a>. Save them with these exact filenames in the same folder named <code>native-host</code>. Open a terminal in its parent directory. If you already have the full project source, run these commands from the project root. Replace all placeholders below with your actual extension ID, CLI path, and model directory; quote paths that contain spaces.',
          command: 'chmod +x native-host/install.sh\n./native-host/install.sh EXTENSION_ID "/absolute/path/to/realesrgan-ncnn-vulkan" "/absolute/path/to/models"',
          note: 'The installer copies the helper and registers com.image_zoom.esrgan for this extension ID. It records the CLI and model paths, so keep those files in place. It currently registers Google Chrome only.',
        },
        {
          title: 'Restart Chrome and trigger AI clarity',
          body: 'Quit Chrome completely, reopen it, and reload your webpage. In the extension popup, choose <strong>AI clarity</strong> under Enlarged image quality. Choose <strong>Faster</strong> or <strong>Better quality</strong>, and trigger AI on <strong>first zoom</strong> or <strong>viewer open</strong>. The defaults are Faster and first zoom. Hold your shortcut key, click a web image, and zoom if using the default trigger. The installed helper is tried automatically.',
        },
      ],
    },
    models: {
      h2: 'Which local model does the popup select?',
      headers: ['Popup setting', 'Local CLI model', 'Required files'],
      rows: [
        ['Faster (default)', 'realesr-general-x4v3', 'realesr-general-x4v3.param + .bin'],
        ['Better quality', 'realesrgan-x4plus', 'realesrgan-x4plus.param + .bin'],
      ],
      note: 'Both local modes produce 4x output. If the Faster model pair is missing, the helper uses the installed x4plus pair. The installer requires x4plus files even when Faster is selected. The labels select models; actual speed and quality depend on the image and device.',
    },
    faq: {
      h2: 'Setup questions and troubleshooting',
      items: [
        ['How can I tell whether the helper ran?', 'The popup has no connected indicator. For a diagnostic check, open DevTools on the webpage and filter Console messages by <code>[ImageZoom][enhancement]</code>. <code>native_cli_fallback</code> means the native attempt failed. A successful <code>upscale_request_applied</code> without native fallback or browser <code>ai_upscale_start</code> is evidence that the native path completed.'],
        ['The helper is unavailable. What should I check?', 'Check the exact extension ID, the executable CLI path, <code>/usr/bin/python3</code>, and the model directory. Confirm both helper files were downloaded with their original names. Quit and reopen Chrome after installation. If the extension ID or CLI/model paths change, rerun the installer with the new values. The ordinary image viewer remains available.'],
        ['What if installation reports missing model files?', 'Use an absolute model directory containing <code>realesrgan-x4plus.param</code> and <code>realesrgan-x4plus.bin</code>. The explicit third argument avoids dependence on the current working directory. Faster additionally uses the <code>realesr-general-x4v3</code> pair when available.'],
        ['Can I connect any RealESRNet or .pth model?', 'This integration uses the Real-ESRGAN NCNN/Vulkan CLI and its supported <code>.param</code>/<code>.bin</code> model pairs. It does not accept arbitrary RealESRNet files or PyTorch <code>.pth</code> checkpoints directly.'],
        ['Has browser AI been removed?', 'No. After a native failure, the extension tries its browser Real-ESRGAN path using LiteRT/WebGPU. That fallback depends on browser and GPU support and model loading. If browser AI cannot run either, the extension uses Lanczos sharpening; you can also choose Quick sharpening or Zoom only in the popup.'],
        ['Do images stay inside the browser?', 'The native path sends image pixels to a local process outside Chrome, on the same device. The helper writes temporary input and output files while the CLI runs and removes the temporary directory afterward. Images may be fetched from their source website, but enhancement does not upload them to a cloud AI service.'],
        ['Can I use the native helper on Windows?', 'The upstream CLI offers Windows builds, but this project’s installer currently registers the Chrome helper only on macOS and Linux. A Windows CLI download alone does not connect it to the extension.'],
      ],
    },
    cta: { h2: 'Your images, a closer look', text: 'Use the free image viewer, then add the local helper when you want native AI enhancement.' },
  },
  zh: {
    title: '本地 Real-ESRGAN 图片高清放大：Chrome 插件设置 | Click Image Zoom',
    description: '为 Chrome 图片放大插件单独安装 Real-ESRGAN 本地助手，在 macOS 或 Linux 上将网页图片放大 4 倍。了解模型准备、Native Messaging 连接与浏览器 AI 后备；图片像素不会上传云端。',
    eyebrow: '可选本地 AI · 安装指南',
    h1: '用本地 <span class="modelName">Real-ESRGAN</span> 高清放大网页图片',
    lead: '让 Click Image Zoom 使用你设备上的 Real-ESRGAN。一次安装本地助手，之后 AI 会自动优先尝试它，再回退到浏览器 AI。',
    setupLink: '安装本地助手',
    back: '返回图片查看器',
    flow: {
      h2: '本地处理路径如何工作',
      text: '插件先从来源网站获取原图。触发 AI 清晰时，Chrome 通过 Native Messaging 将图片交给已安装的本地助手。',
      nodes: [['Chrome 插件', '选择图片，触发 AI 清晰'], ['本地助手', 'Chrome Native Messaging · Python'], ['Real-ESRGAN CLI', '本地模型推理 · 4 倍输出']],
      note: '原生路径的结果会回到查看器。本地助手未安装或失败时，插件会尝试基于 LiteRT/WebGPU 的浏览器 AI；仍不可用时改用 Lanczos 快速清晰。图片像素不会上传到云端 AI 服务。',
    },
    requirements: {
      h2: '安装前需要准备什么',
      text: '本地助手是可选的。免费的图片查看器、10 倍缩放和拖动查看都不需要它。原生 AI 固定输出 4 倍结果，无法恢复原图中不存在的文字或信息。',
      items: [
        ['支持的平台', '目前支持 macOS 或 Linux 上的 Google Chrome。虽然上游 CLI 有 Windows 版本，本项目的 Native Messaging 安装器尚不支持 Windows。'],
        ['Python 与本地文件', '安装器直接调用 /usr/bin/python3，助手还需要 PATH 能找到 python3。两者都应可用；仅使用 Python 标准库，不需要安装 pip 包。CLI 与 .param/.bin 模型文件应保存在长期保留的本地目录。'],
        ['设备条件', '选择与操作系统和 GPU 兼容的上游 CLI。处理时间、内存占用和模型可用性因设备而异。'],
      ],
    },
    install: {
      h2: '四步安装并连接',
      intro: '使用你实际安装的插件 ID 和本地绝对路径。',
      steps: [
        {
          title: '安装插件并复制真实 ID',
          body: '从 Chrome 应用商店添加 Click Image Zoom。打开 <code>chrome://extensions</code>，开启开发者模式，复制 Click Image Zoom 卡片上显示的 ID。开发用未打包插件也应使用它实际显示的 ID。',
        },
        {
          title: '下载 CLI 与模型文件',
          body: '从 <a href="https://github.com/xinntao/Real-ESRGAN-ncnn-vulkan/releases" target="_blank" rel="noopener">Real-ESRGAN-ncnn-vulkan 官方发布页</a>下载适合操作系统的压缩包并解压。模型目录必须包含 <code>realesrgan-x4plus.param</code> 和 <code>realesrgan-x4plus.bin</code>。速度优先模型还需 <code>realesr-general-x4v3.param</code> 与 <code>realesr-general-x4v3.bin</code> 成对文件。模型背景可查看 <a href="https://github.com/xinntao/Real-ESRGAN" target="_blank" rel="noopener">Real-ESRGAN 官方项目</a>。',
        },
        {
          title: '向 Chrome 注册本地助手',
          body: '分别下载 <a href="/downloads/native-host/install.sh" download="install.sh">install.sh</a> 和 <a href="/downloads/native-host/host.py" download="host.py">host.py</a>，保留这两个原文件名，放进同一个名为 <code>native-host</code> 的文件夹。在该文件夹的上一级目录打开终端。已有完整项目源码时，从项目根目录执行以下命令。把占位值替换为真实插件 ID、CLI 与模型目录的绝对路径；路径含空格时保留引号。',
          command: 'chmod +x native-host/install.sh\n./native-host/install.sh EXTENSION_ID "/absolute/path/to/realesrgan-ncnn-vulkan" "/absolute/path/to/models"',
          note: '安装器会复制助手，并为这个插件 ID 注册 com.image_zoom.esrgan，记录 CLI 与模型路径。请保留原来的 CLI 和模型文件位置；目前只注册 Google Chrome。',
        },
        {
          title: '重启 Chrome，触发 AI 清晰',
          body: '完全退出 Chrome 后重新打开，再刷新网页。在插件弹窗的“放大图片画质”中选择 <strong>AI 清晰</strong>，选择<strong>速度优先</strong>或<strong>画质优先</strong>，将触发时机设为<strong>首次放大</strong>或<strong>打开图片</strong>。默认是速度优先与首次放大。按住快捷键点击网页图片，使用默认触发时机时再滚轮放大。本地助手会自动优先尝试。',
        },
      ],
    },
    models: {
      h2: '弹窗选项对应哪个本地模型',
      headers: ['弹窗选项', '本地 CLI 模型', '所需文件'],
      rows: [
        ['速度优先（默认）', 'realesr-general-x4v3', 'realesr-general-x4v3.param + .bin'],
        ['画质优先', 'realesrgan-x4plus', 'realesrgan-x4plus.param + .bin'],
      ],
      note: '两种本地模式都输出 4 倍结果。速度优先模型缺失时，助手会使用已有的 x4plus 文件。即使选择速度优先，安装器也要求 x4plus 文件齐全。选项用于选择模型，实际速度与画质取决于图片和设备。',
    },
    faq: {
      h2: '安装问题与排障',
      items: [
        ['怎么确认本地助手运行了？', '弹窗没有“已连接”状态。需要诊断时，在网页的 DevTools Console 筛选 <code>[ImageZoom][enhancement]</code>。出现 <code>native_cli_fallback</code> 表示原生尝试失败；成功出现 <code>upscale_request_applied</code>，且没有原生回退或浏览器的 <code>ai_upscale_start</code>，可作为原生路径完成的证据。'],
        ['本地助手不可用时先检查什么？', '核对真实插件 ID、CLI 可执行文件绝对路径、<code>/usr/bin/python3</code> 和模型目录。确认两份助手文件都已下载，文件名没有变化；安装后完全退出并重开 Chrome。插件 ID 或 CLI/模型路径变化时，用新值重新运行安装器。普通图片查看器仍可使用。'],
        ['安装器提示缺少模型文件怎么办？', '传入包含 <code>realesrgan-x4plus.param</code> 与 <code>realesrgan-x4plus.bin</code> 的绝对路径目录。显式第三个参数可避免依赖当前工作目录。速度优先还会在可用时使用 <code>realesr-general-x4v3</code> 成对文件。'],
        ['能直接接入任意 RealESRNet 或 .pth 模型吗？', '当前接入的是 Real-ESRGAN 的 NCNN/Vulkan CLI，使用它支持的 <code>.param</code>/<code>.bin</code> 成对文件，不能直接接入任意 RealESRNet 文件或 PyTorch <code>.pth</code> 检查点。'],
        ['浏览器 AI 已经被移除了吗？', '没有。本地助手失败后，插件仍会尝试 LiteRT/WebGPU 的浏览器 Real-ESRGAN 路径，它依赖浏览器、GPU 支持和模型加载。浏览器 AI 也不可用时改用 Lanczos 快速清晰；也可以直接在弹窗选择“快速清晰”或“仅缩放”。'],
        ['图片始终不离开浏览器吗？', '原生路径会把像素交给同一设备上 Chrome 之外的本地进程。助手运行 CLI 时写入临时输入与输出文件，结束后删除临时目录。原图可能从来源网站获取，但增强不会上传到云端 AI 服务。'],
        ['Windows 能用本地助手吗？', '上游 CLI 提供 Windows 版本，但本项目的安装器目前只为 macOS 和 Linux 注册 Chrome 助手。仅下载 Windows CLI 不会自动与插件连接。'],
      ],
    },
    cta: { h2: '看清图片，从查看器开始', text: '免费使用网页图片查看器，需要原生 AI 增强时再安装本地助手。' },
  },
}

export const legal = {
  privacy: {
    path: '/privacy/',
    file: 'privacy.html',
    title: 'Privacy Policy | Click Image Zoom',
    h1: 'Privacy Policy',
    description: 'How Click Image Zoom handles extension settings, webpage images, local AI processing, browser permissions, downloads, and website request data.',
  },
  terms: {
    path: '/terms/',
    file: 'terms.html',
    title: 'Terms of Service | Click Image Zoom',
    h1: 'Terms of Service',
    description: 'Terms for using the Click Image Zoom website and Chrome extension, including acceptable use, local processing, third-party content, and limitations.',
  },
}
